[package]
name = "s2k"
version = "0.1.0"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
argon2 = { version = "0.5.3", features = ["std"] }
base64 = "0.22.1"
futures = "0.3.31"
# https://docs.rs/getrandom/0.3.1/getrandom/index.html#webassembly-support
getrandom = { version = "0.3.1", features = ["wasm_js"] }
gloo = { version = "0.11.0", default-features = false, features = ["futures", "storage", "timers"] }
sha2 = "0.10.8"
strum = { version = "0.27.1", features = ["derive"] }
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["Clipboard", "HtmlSelectElement", "Navigator"] }
yew = { version = "0.21.0", features = ["csr"] }

[dev-dependencies]
hex-literal = "1.0.0"
