[package]
name = "s2k"
version = "0.1.0"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
clap = { version = "3", features = ["derive"] }
dirs = "4"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
toml = "0.5"

[dev-dependencies]
hex-literal = "0.3"
