[package]
name = "s2k"
version = "0.1.0"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
clap = "3.0.0-beta.5"
dirs = "4.0"
serde = { version = "1", features = ["derive"] }
sha2 = "0.9"
toml = "0.5"

[dev-dependencies]
hex-literal = "0.3"
